language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  chmod +x gradlew

# Travis CI 서버 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-webservice-freelec *
  - mkdir -p deploy
  - mv springboot-webservice-freelec.zip deploy/springboot-webservice-freelec.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-webservice-freelec-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-webservice-freelec-build
    key: springboot-webservice-freelec.zip
    bundle_type: zip
    application: springboot-webservice-freelec
    deployment_group: springboot-webservice-freelec-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람

notifications:
  email:
    recipients:
      - xlffm3@naver.com
